### ISSUE TITLE
Issues with latest version of terraform

### ISSUE THREAD

**Issue by ecout** [dumrauf/s3-helm-chart-repo-with-docs#1]
Hello. The following version:
`terraform version
Terraform v0.12.15
+ provider.aws v2.36.0
+ provider.local v1.4.0
+ provider.template v2.1.2`

Throws the following syntax errors:
`
Error: Unsupported block type

  on main.tf line 26, in resource "aws_s3_bucket" "helm-chart-repository":
  26:   tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.

Error: Unsupported block type

  on outputs.tf line 11, in data "template_file" "helm-chart-repository-index-md":
  11:   vars {

Blocks of type "vars" are not expected here. Did you mean to define argument
"vars"? If so, use the equals sign to assign it a value.

Error: Unsupported block type

  on outputs.tf line 23, in data "template_file" "helm-chart-repository-index-html":
  23:   vars {

`

Downgrading to 0.11.4 parsed the code correctly

`+ aws_s3_bucket.helm-chart-repository
      id:                                                       <computed>
      acceleration_status:                                      <computed>
      acl:                                                      "public-read"
      arn:                                                      <computed>
      bucket:                                                   "boingodev-helm-repository"
      bucket_domain_name:                                       <computed>
      bucket_regional_domain_name:                              <computed>
      force_destroy:                                            "false"
      hosted_zone_id:                                           <computed>
      logging.#:                                                "1"
      logging.1433227981.target_bucket:                         "aws-logs-899159142448-us-west-2"
      logging.1433227981.target_prefix:                         "boingodev/boingodev-helm-repository/"
      region:                                                   <computed>
      request_payer:                                            <computed>
      tags.%:                                                   "2"
      tags.Helm-Chart-Repository:                               "1"
      tags.Terraform:                                           "1"
      versioning.#:                                             "1"
      versioning.0.enabled:                                     "true"
      versioning.0.mfa_delete:                                  "false"
      website.#:                                                "1"
      website.0.index_document:                                 "index.html"
      website_domain:                                           <computed>
      website_endpoint:                                         <computed>

  + aws_s3_bucket_object.helm-chart-repository-index-html
      id:                                                       <computed>
      acl:                                                      "private"
      bucket:                                                   "boingodev-helm-repository"
      content:                                                  "${data.template_file.helm-chart-repository-index-html.rendered}"
      content_type:                                             "text/html"
      etag:                                                     "${md5(\"${data.template_file.helm-chart-repository-index-html.rendered}\")}"
      force_destroy:                                            "false"
      key:                                                      "index.html"
      server_side_encryption:                                   <computed>
      storage_class:                                            <computed>
      version_id:                                               <computed>

  + aws_s3_bucket_policy.helm-chart-repository-bucket-policy
      id:                                                       <computed>
      bucket:                                                   "${aws_s3_bucket.helm-chart-repository.id}"
      policy:                                                   "${data.aws_iam_policy_document.helm-chart-repository-policy-document.json}"

  + local_file.helm-chart-repository-index-html
      id:                                                       <computed>
      content:                                                  "${data.template_file.helm-chart-repository-index-html.rendered}"
      directory_permission:                                     "0777"
      file_permission:                                          "0777"
      filename:                                                 "/Users/ecoutin/Documents/AWS/Ansible/Repositories/EKS/eks-tools/helm/s3/s3-helm-chart-repo-with-docs-master/boingodev-helm-repository.index.html"

  + local_file.helm-chart-repository-index-md
      id:                                                       <computed>
      content:                                                  "${data.template_file.helm-chart-repository-index-md.rendered}"
      directory_permission:                                     "0777"
      file_permission:                                          "0777"
      filename:                                                 "/Users/ecoutin/Documents/AWS/Ansible/Repositories/EKS/eks-tools/helm/s3/s3-helm-chart-repo-with-docs-master/boingodev-helm-repository.index.md"

Plan: 5 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

`

**Comment by dumrauf** [comment]
Hi @ecout,

Thanks for opening the issue. You're absolutely correct in the sense that only Terraform 0.11 is currently supported.

I've taken the opportunity and upgraded the master branch to Terraform v0.12 (this seems to be the version the world is on these days). For legacy reasons, I've also kept a version that is compliant with Terraform v0.11 in branch [terraform@0.11](https://github.com/dumrauf/s3-helm-chart-repo-with-docs/tree/terraform%400.11).

I hope this helps. Feel free to open another issue if need be.

Thanks,
 Dominic
